core/urls.py
from django.urls import path
from . import views
from .views import login_view, logout_view, dashboard

app_name = 'core'  # <-- define o namespace aqui

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('', dashboard, name='dashboard'),
    path('dashboard/', dashboard),
]

financeiro/urls.py
from django.urls import path
from . import views
from .views import gerar_carne_pdf

app_name = 'financeiro'

urlpatterns = [
    path('caixa/listar/', views.lista_caixa, name='lista_caixa'),# Lista vazia - nenhuma URL definida
    path('caixa/cadastrar/', views.caixa_cadastrar, name='caixa_cadastrar'),
    path('caixa/pdf/', views.caixa_pdf, name='caixa_pdf'),  # Exemplo
    path('contrato/cadastrar/', views.contrato_cadastrar, name='contrato_cadastrar'),
    path('contrato/listar/', views.contrato_listar, name='contrato_listar'),
    path('contrato/editar/<int:pk>/', views.contrato_editar, name='contrato_editar'),
    path('contrato/excluir/<int:pk>/', views.contrato_excluir, name='contrato_excluir'),
    path('parcela/receber/<int:parcela_id>/', views.parcela_receber, name='parcela_receber'),
    path('plano/cadastrar/', views.plano_cadastrar, name='plano_cadastrar'),
    path('paciente/<int:paciente_id>/', views.paciente_ficha, name='paciente_ficha'),
    path('contrato/paciente/<int:paciente_id>/', views.contrato_paciente, name='contrato_paciente'),
    path('buscar/', views.buscar_paciente, name='buscar_paciente'),
    path('autocomplete-paciente/', views.autocomplete_paciente, name='autocomplete_paciente'),
    path('contrato/exportar-pdf/', views.contrato_exportar_pdf, name='contrato_exportar_pdf'),
    path('caixa/editar/<int:pk>/', views.editar_caixa, name='editar_caixa'),
    path('caixa/excluir/<int:pk>/', views.excluir_caixa, name='excluir_caixa'),
    path('contrato/<int:contrato_id>/carne/', views.gerar_carne_pdf, name='gerar_carne_pdf'),
    path('plano/editar/<int:pk>/', views.plano_editar, name='plano_editar'),
    path('parcela/relatorio-parcelas/', views.relatorio_parcelas, name='relatorio_parcelas'),
    path('parcela/estornar/<int:parcela_id>/', views.estornar_parcela, name='estornar_parcela'),
    path('parcela/excluir/<int:parcela_id>/', views.excluir_parcela, name='excluir_parcela'),
]

sysodont/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),  # raiz direciona para core
    path('agendamento/', include('agendamento.urls', namespace='agendamento')),
    path('paciente/', include('paciente.urls', namespace= 'paciente')),
    path('financeiro/', include('financeiro.urls', namespace= 'financeiro')),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
]

financeiro/models.py
from django.db import models
from django.contrib.auth import get_user_model
from datetime import date
from paciente.models import Paciente
from django.utils.safestring import mark_safe
from django.urls import reverse


User = get_user_model()

class Plano(models.Model):
    nome = models.CharField(max_length=100, verbose_name="NOME")
    descricao = models.TextField(blank=True, verbose_name="DESCRIÇÃO")
    valor = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="VALOR")
    periodo = models.PositiveIntegerField(default=12, verbose_name="PARCELAS")  # em meses

    def __str__(self):
        return self.nome


class Contrato(models.Model):
    STATUS_CONTRATO_CHOICES = [
        ('ativo', 'ATIVO'),
        ('pendente', 'PENDENTE'),
        ('cancelado', 'CANCELADO'),
        ]
    
    paciente = models.ForeignKey('paciente.Paciente', on_delete=models.CASCADE, verbose_name='Paciente')
    plano = models.ForeignKey(Plano, on_delete=models.CASCADE, verbose_name='Plano')
    data_adesao = models.DateField(default=date.today, verbose_name='Adesão')
    dia_vencimento = models.IntegerField(choices=[(d, f"Dia {d}") for d in [5, 10, 15, 20, 25, 30]], verbose_name='Vencimento')
    numero_contrato = models.CharField(max_length=20, unique=True, verbose_name='Contrato')
    status_contrato = models.CharField(max_length=20, verbose_name='Status', choices=STATUS_CONTRATO_CHOICES, null=True, blank=True)
    
    def __str__(self):
        return f"Contrato {self.numero_contrato} - {self.paciente.nome}"
    
    def parcelas_em_html(self, obj):
     parcelas_em_aberto = obj.parcelas.filter(status='aberto').order_by('data_vencimento')
     parcelas_pagas = obj.parcelas.filter(status='pago').order_by('data_vencimento')

     html = ""

     if parcelas_em_aberto.exists():
        html += "<h4 style='color: #a94442;'>🔴 Parcelas em Aberto</h4>"
        for p in parcelas_em_aberto:
            link = f"/admin/financeiro/parcela/{p.id}/change/"
            html += (
                f"<div style='margin-bottom: 5px; background-color:#f2dede; padding:10px; border-radius:5px;'>"
                f"<strong>Venc:</strong> {p.data_vencimento} | "
                f"<strong>Valor:</strong> R$ {p.valor} | "
                f"<strong>Status:</strong> Em aberto | "
                f"<a href='{link}' target='_blank'>Dar Baixa</a></div>"
            )

     if parcelas_pagas.exists():
       html += "<h4 style='color: #3c763d;'>🟢 Parcelas Pagas</h4>"
     for p in parcelas_pagas:
        link = f"/admin/financeiro/parcela/{p.id}/change/"
        valor_pago = p.valor_pago if p.valor_pago is not None else p.valor
        data_pagamento = p.data_pagamento.strftime('%d/%m/%Y') if p.data_pagamento else "-"
        forma_pagamento = dict(p.FORMA_PAGAMENTO_CHOICES).get(p.forma_pagamento, '-') if p.forma_pagamento else "-"

        html += (
            f"<div style='margin-bottom: 5px; background-color:#dff0d8; padding:10px; border-radius:5px;'>"
            f"<strong>Venc:</strong> {p.data_vencimento.strftime('%d/%m/%Y')} | "
            f"<strong>Pago em:</strong> {data_pagamento} | "
            f"<strong>Forma:</strong> {forma_pagamento} | "
            f"<strong>Valor:</strong> R$ {valor_pago:.2f} | "
            f"<strong>Status:</strong> Pago | "
            f"<a href='{link}' target='_blank'>Visualizar</a></div>"
        )

     if not html:
        html = "Nenhuma parcela cadastrada."

     return mark_safe(html)

#parcelas_em_html.short_description = "Financeiro"
    
class Parcela(models.Model):
    FORMA_PAGAMENTO_CHOICES = [
        ('dinheiro', 'Dinheiro'),
        ('pix_pj', 'Pix PJ'),
        ('pix_pf', 'Pix PF'),
        ('cartao_credito', 'Cartão de crédito'),
        ('cartao_debito', 'Cartão de débito'),
    ]

    contrato = models.ForeignKey(Contrato, on_delete=models.CASCADE, related_name='parcelas')
    numero = models.PositiveIntegerField(verbose_name="Parcela")
    data_vencimento = models.DateField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    valor_pago = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)  # <== ADICIONADO
    status = models.CharField(max_length=20, choices=[('aberto', 'Aberto'), ('pago', 'Pago')], default="aberto")
    data_pagamento = models.DateField(null=True, blank=True)
    forma_pagamento = models.CharField(max_length=20, choices=FORMA_PAGAMENTO_CHOICES, null=True, blank=True)
    observacao = models.TextField(blank=True)

    @property
    def dias_atraso(self):
        if self.status != 'pago' and self.data_vencimento < date.today():
            return (date.today() - self.data_vencimento).days
        return 0

    def __str__(self):
        return f"Parcela {self.numero} - {self.contrato.numero_contrato}"


class Caixa(models.Model):
    PLANO_DE_CONTAS = [
        ('Consultorio', 'Despesa do Consultório'),
        ('Boletos', 'Boletos'),
        ('Outros', 'Outros'),
        ('Planos', 'Planos'),
        ('Procedimento', 'Procedimento Particular')
    ]

    FORMA_CHOICES = [
        ('dinheiro', 'Dinheiro'),
        ('pix_pj', 'Pix PJ'),
        ('pix_pf', 'Pix PF'),
        ('cartao_credito', 'Cartão de crédito'),
        ('cartao_debito', 'Cartão de débito'),
    ]

    TIPO_CHOICES = [
     ('entrada', 'Entrada'), 
     ('saida', 'Saída'),
    ]

    data = models.DateField(default=date.today)
    descricao = models.CharField(max_length=255)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    tipo = models.CharField(max_length=10, choices=[('entrada', 'Entrada'), ('saida', 'Saída')])
    forma = models.CharField(max_length=20, choices=FORMA_CHOICES)
    plano_conta = models.CharField(max_length=30, choices=PLANO_DE_CONTAS, default='outros')
    observacao = models.TextField(blank=True)

    def __str__(self):
        return f"{self.tipo.upper()} - R$ {self.valor} ({self.get_plano_conta_display()})"

financeiro/forms.py
from django import forms
from .models import Contrato, Caixa, Parcela, Plano

class ContratoForm(forms.ModelForm):
    class Meta:
        model = Contrato
        fields = ['paciente', 'plano', 'data_adesao', 'dia_vencimento', 'numero_contrato', 'status_contrato']
        widgets = {
            'data_adesao': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'paciente': forms.Select(attrs={'class': 'form-control'}),
            'plano': forms.Select(attrs={'class': 'form-control'}),
            'dia_vencimento': forms.Select(attrs={'class': 'form-control'}),
            'numero_contrato': forms.TextInput(attrs={'class': 'form-control'}),
            'status_contrato': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'paciente' in self.fields:
            self.fields['paciente'].disabled = True

class CaixaForm(forms.ModelForm):
    class Meta:
        model = Caixa
        fields = ['data', 'descricao', 'valor', 'tipo', 'forma', 'plano_conta', 'observacao']
        widgets = {
            'data': forms.DateInput(attrs={
                'type': 'date', 
                'class': 'form-control',
                'autocomplete': 'off'
            }),
            'descricao': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Descrição do lançamento'
            }),
            'valor': forms.NumberInput(attrs={
                'class': 'form-control',
                'step': '0.01',
                'placeholder': '0,00'
            }),
            'tipo': forms.Select(attrs={
                'class': 'form-select',
                'id': 'tipo-lancamento'
            }),
            'forma': forms.Select(attrs={
                'class': 'form-select',
                'id': 'forma-pagamento'
            }),
            'plano_conta': forms.Select(attrs={
                'class': 'form-select',
                'id': 'plano-conta'
            }),
            'observacao': forms.Textarea(attrs={
                'class': 'form-control', 
                'rows': 2,
                'placeholder': 'Observações adicionais'
            }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Defina valores padrão se necessário
        self.fields['tipo'].empty_label = 'Selecione o tipo'
        self.fields['forma'].empty_label = 'Selecione a forma'
        self.fields['plano_conta'].empty_label = 'Selecione o plano'

class ParcelaReceberForm(forms.ModelForm):
    class Meta:
        model = Parcela
        fields = ['valor_pago', 'status', 'data_pagamento', 'forma_pagamento', 'observacao']
        widgets = {
            'valor_pago': forms.NumberInput(attrs={
                'class': 'form-control',
                'step': '0.01',
                'min': '0',
            }),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'data_pagamento': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'forma_pagamento': forms.Select(attrs={'class': 'form-control'}),
            'observacao': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

class PlanoForm(forms.ModelForm):
    class Meta:
        model = Plano
        fields = ['nome', 'descricao', 'valor', 'periodo']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control'}),
            'valor': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01'}),
            'periodo': forms.TextInput(attrs={'class': 'form-control'}),
        }                       

financeiro/templates/financeiro/plano/plano_cadastrar.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
            <div class="card shadow">
                <div class="card-header py-3 bg-primary text-white">
                    <h4 class="mb-0">
                     <i class="fas fa-plus-circle me-2"></i> Cadastrar Planos
                    </h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="row g-3">

                            <div class="col-md-6">
                                <label for="id_nome">Nome:</label>
                                {{ form.nome }}
                            </div>

                            <div class="col-md-6">
                                <label for="id_descricao">Descrição:</label>
                                {{ form.descricao }}
                            </div>

                            <div class="col-md-4">
                                <label for="id_valor">Valor:</label>
                                {{ form.valor }}
                            </div>

                            <div class="col-md-4">
                                <label for="id_observacao">Parcelas:</label>
                                {{ form.periodo }}
                            </div>

                        </div>

                        <div class="d-flex justify-content-end mt-4">
                            <button type="submit" class="btn btn-success me-2">
                                <i class="fas fa-save"></i> Salvar
                            </button>
                            <a href="{% url 'financeiro:plano_cadastrar' %}" class="btn btn-secondary">
                                <i class="fas fa-arrow-left"></i> Voltar
                            </a>
                        </div>

                    </form>
                </div>
            </div>

            <div class="card mt-4 shadow">
                <div class="card-header py-3 bg-primary text-white">
                    <h4 class="mb-0">
                     <i class="fas fa-clipboard-list me-2"></i> Planos Cadastrados
                    </h4>
                </div>
                <div class="card-body">
                    {% if planos %}
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Descrição</th>
                                <th>Valor</th>
                                <th>Parcelas</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for plano in planos %}
                            <tr>
                                <td>{{ plano.nome }}</td>
                                <td>{{ plano.descricao }}</td>
                                <td>{{ plano.valor }}</td>
                                <td>{{ plano.periodo }}</td>
                                <td class="text-center">
                                  <div class="btn-group btn-group-sm" role="group">
                                      <a href="{% url 'financeiro:plano_editar' plano.id %}" class="btn btn-outline-primary" title="Abrir">
                                         <i class="fas fa-edit"></i>
                                      </a>
                                    </div>
                                </td>      
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <p>Nenhum plano cadastrado.</p>
                    {% endif %}
                </div>
            </div>
        </div>
{% endblock %}